info:
  contact: {}
paths:
  /api/chat:
    get:
      description: Endpoint for testing by returning Hello World
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: ""
        "500":
          description: ""
      summary: Testing Endpoint
      tags:
      - /chat
  /api/chat/user:
    post:
      description: Endpoint for setting user data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Set user data for messages
      tags:
      - /chat/user
swagger: "2.0"
